mysql:
  dialect: "mysql"
  database: "pop_test"
  host: {{ envOr "MYSQL_HOST" "localhost"  }}
  port: {{ envOr "MYSQL_PORT" "3306"  }}
  user: {{ envOr "MYSQL_USER"  "root"  }}
  password: {{ envOr "MYSQL_PASSWORD"  "root"  }}

mysql_travis:
  dialect: "mysql"
  database: "pop_test"
  host: {{ envOr "MYSQL_HOST" "localhost"  }}
  port: {{ envOr "MYSQL_PORT" "3306"  }}
  user: {{ envOr "MYSQL_USER"  "root"  }}
  password: {{ envOr "MYSQL_PASSWORD"  ""  }}

postgres:
  url: "postgres://postgres:postgres@localhost:5432/pop_test?sslmode=disable"
  pool: 25

sqlite:
  dialect: "sqlite3"
  database: "./sql_scripts/sqlite/test.sqlite"

mssql:
  url: "mssql://postgres:postgres@localhost:5432/pop_test?sslmode=disable"
  dialect: "mssql"
  host: {{ envOr "MSSQL_HOST" "localhost"  }}
  port: {{ envOr "MSSQL_PORT" "1533"  }}
  user: {{ envOr "MSSQL_USER"  "root"  }}
  password: {{ envOr "MSSQL_PASSWORD"  ""  }}
